### ISSUE TITLE
azd up fails on provisiong step - seems to fail on postgres.

### ISSUE THREAD

**Issue by alexwolfmsft** [Azure-Samples/msdocs-flask-postgresql-sample-app#35]
This template fails to run when azd up is executed.

### Minimal steps to reproduce
azd init --template (name)
azd up

### Any log messages given by the failure
"Deployment error details: ParameterOutOfRange: The value of the version should be in []. Verify that the specified paramter value is correct."

### Expected/desired behavior
azd up completes and provisions/deploys app

### OS and Version?
Windows 10

### Versions
>

### Mention any other details that might be useful

Used Eastus2 region, was running both locally and in cloudshell.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
This is the error message shown when PostgreSQL flexible servers are not permitted in the given location. This more commonly happens for Microsoft employees who have more constrained locations than external customers. If you get this error, choose another location, like eastus.

**Comment by pamelafox** [comment]
You can close this issue since I don't think there's anything we can do in this repo, I will continue trying to get the PostgreSQL team to improve the error message.
